/**
 * CLAUDE.md Generator
 * Produces a cascaded context file that each agent reads to understand:
 * 1. The overall project context (from root node)
 * 2. The component hierarchy (parent system prompts)
 * 3. The agent's specific task and constraints
 * 4. Shared contracts and dependencies
 *
 * Cascade model: child inherits all parent context, adding specificity at each level.
 */
import { getDb } from '../db';

interface NodeRow {
  id: string;
  parent_id: string | null;
  name: string;
  depth: number;
  status: string;
  node_type: string;
  prompt: string | null;
  role: string | null;
  system_prompt: string | null;
  allowed_paths: string | null;
  dependencies: string | null;
  acceptance_criteria: string | null;
  context_files: string | null;
  max_iterations: number;
  escalation_policy: string;
  model: string;
}

/**
 * Walk up the tree to collect all ancestor nodes, ordered from root to current.
 */
function getAncestors(nodeId: string): NodeRow[] {
  const db = getDb();
  const ancestors: NodeRow[] = [];
  let currentId: string | null = nodeId;

  while (currentId) {
    const node = db.prepare('SELECT * FROM nodes WHERE id = ?').get(currentId) as NodeRow | undefined;
    if (!node) break;
    ancestors.unshift(node); // prepend so root comes first
    currentId = node.parent_id;
  }

  return ancestors;
}

/**
 * Get contracts applicable to this node (contracts from parent node).
 */
function getApplicableContracts(nodeId: string): Array<{ name: string; content: string | null }> {
  const db = getDb();
  const node = db.prepare('SELECT parent_id FROM nodes WHERE id = ?').get(nodeId) as { parent_id: string | null } | undefined;
  if (!node?.parent_id) return [];

  return db.prepare('SELECT name, content FROM contracts WHERE parent_node_id = ?')
    .all(node.parent_id) as Array<{ name: string; content: string | null }>;
}

/**
 * Get sibling nodes for dependency context.
 */
function getSiblingInfo(nodeId: string): Array<{ name: string; role: string | null; status: string }> {
  const db = getDb();
  const node = db.prepare('SELECT parent_id FROM nodes WHERE id = ?').get(nodeId) as { parent_id: string | null } | undefined;
  if (!node?.parent_id) return [];

  return db.prepare('SELECT name, role, status FROM nodes WHERE parent_id = ? AND id != ?')
    .all(node.parent_id, nodeId) as Array<{ name: string; role: string | null; status: string }>;
}

/**
 * Generate the CLAUDE.md content for a given node.
 * This is the primary context document the agent will read.
 */
export function generateClaudeMd(nodeId: string): string {
  const db = getDb();
  const node = db.prepare('SELECT * FROM nodes WHERE id = ?').get(nodeId) as NodeRow | undefined;
  if (!node) throw new Error(`Node ${nodeId} not found`);

  const ancestors = getAncestors(nodeId);
  const rootNode = ancestors[0];
  const contracts = getApplicableContracts(nodeId);
  const siblings = getSiblingInfo(nodeId);

  const allowedPaths: string[] = node.allowed_paths ? JSON.parse(node.allowed_paths) : [];
  const dependencies: string[] = node.dependencies ? JSON.parse(node.dependencies) : [];
  const contextFiles: string[] = node.context_files ? JSON.parse(node.context_files) : [];

  // Build architecture summary from ancestor chain
  const architectureSummary = ancestors
    .slice(1) // skip root (already shown in project context)
    .map(a => `- **${a.name}** (${a.role || 'Agent'}): ${a.prompt?.substring(0, 100) || ''}...`)
    .join('\n') || '(This is a top-level component)';

  // Format contracts
  const contractsSection = contracts.length > 0
    ? contracts.map(c => `### ${c.name}\n\`\`\`\n${c.content || '(not yet defined)'}\n\`\`\``).join('\n\n')
    : '_No shared contracts defined for this scope._';

  // Format dependencies
  const dependenciesSection = dependencies.length > 0
    ? dependencies.map(dep => {
        const sibling = siblings.find(s => s.name === dep);
        return `- **${dep}** — Status: ${sibling?.status || 'unknown'}`;
      }).join('\n')
    : '_No dependencies on sibling components._';

  // Build escalation policy description
  const escalationDesc = {
    'ask_human': 'Stop and ask for human input via a clear, formatted message',
    'auto_retry': 'Retry the operation with a different approach',
    'fail': 'Mark the task as failed and log the reason'
  }[node.escalation_policy] || 'Stop and report';

  return `# CLAUDE.md — Agent Configuration
<!-- Auto-generated by Agent Tree Orchestrator. Do not edit manually. -->

# === PROJECT CONTEXT ===
${rootNode.system_prompt || rootNode.prompt || 'No project context available.'}

# === ARCHITECTURE ===
Component hierarchy from root to this node:
${architectureSummary}

# === COMPONENT CONTEXT ===
${ancestors.length > 1 ? ancestors[ancestors.length - 2].system_prompt || '' : ''}

# === YOUR CONFIGURATION ===
## Role: ${node.role || 'Software Engineer'}
## Name: ${node.name}
## Type: ${node.node_type}
## Model: ${node.model}

## Task
${node.prompt || 'No task prompt defined.'}

## File Boundaries
You may ONLY create or modify files within these paths:
${allowedPaths.length > 0 ? allowedPaths.map(p => `- \`${p}\``).join('\n') : '- (No restrictions specified - use good judgment)'}

**IMPORTANT:** Do not read or write files outside your designated paths.
The \`enforce_boundaries.py\` hook will block violations automatically.

## Shared Contracts
These interfaces define how you interact with sibling components:

${contractsSection}

## Dependencies
Your work depends on these sibling components completing first:

${dependenciesSection}

## Context Files
Additional files provided for context (read-only unless in your allowed paths):
${contextFiles.length > 0 ? contextFiles.map(f => `- \`${f}\``).join('\n') : '_(none)_'}

## Acceptance Criteria
Your work is complete when ALL of the following are satisfied:

${node.acceptance_criteria || '- Task is functionally complete\n- All tests pass\n- No TypeScript errors'}

## Execution Constraints
- **Max iterations:** ${node.max_iterations}
- **Escalation policy:** If you cannot complete the task within ${node.max_iterations} turns — ${escalationDesc}

## Working Guidelines
1. Read existing code before writing new code
2. Make incremental, testable changes
3. Run tests after each significant change
4. Update contracts if you change shared interfaces
5. Document complex decisions in code comments
6. If you find a bug outside your scope, document it but don't fix it
`;
}

/**
 * Generate a simple CLAUDE.md for the root/project level.
 */
export function generateRootClaudeMd(projectId: string): string {
  const db = getDb();
  const project = db.prepare('SELECT p.*, n.system_prompt, n.prompt FROM projects p LEFT JOIN nodes n ON p.root_node_id = n.id WHERE p.id = ?').get(projectId) as {
    name: string;
    system_prompt: string | null;
    prompt: string | null;
  } | undefined;

  if (!project) throw new Error(`Project ${projectId} not found`);

  return `# CLAUDE.md — Project Root
## Project: ${project.name}

${project.system_prompt || project.prompt || ''}

## Architecture
This project uses the Agent Tree Orchestrator pattern:
- Each component is developed by a specialized AI agent
- Agents communicate through defined contracts
- Changes outside designated file boundaries are blocked
- Every component has a corresponding testing agent
`;
}
